### ISSUE TITLE
Lisibilité message Git

### ISSUE THREAD

**Issue by florianbouvot** [MoOx/vscode-color-theme-dark-sea#1]
Bonjour @MoOx,

J'utilise le thème depuis hier et je remarque que la zone de message dans le contrôle de code source n'est pas très lisible (contraste est très faible).

![capture d ecran 2018-12-14 a 10 05 50](https://user-images.githubusercontent.com/2061540/49993751-d7251680-ff87-11e8-9a8f-607796c8fadd.png)

Merci en tout cas, Florian.

**Comment by MoOx** [comment]
Should be good in 1.0.1.

**Comment by florianbouvot** [comment]
Yes thank you.
